"""
nvdiffrast-based renderer for the MegaPose 3D models (Google Scanned Objects and
ShapeNetCoreV2). For each object it samples Hammersley viewpoints on a sphere and renders
either base color (shading_mode='texture') or world-space normals (shading_mode='normal').

The base-color pass writes a transforms.json per object; the normal pass reuses those same
poses by reading transforms.json from the matching renders3-color folder, so run the
'texture' pass before the 'normal' pass.

GSO vs ShapeNet are auto-detected from mesh_root (the ShapeNet branch is used when the path
contains 'shapenetcorev2'); they differ in mesh folder layout and normalization.
"""

import argparse
import json
import os
import numpy as np
import torch
import nvdiffrast.torch as dr
from tqdm import tqdm
import trimesh
from PIL import Image
import cv2
from typing import Tuple, Dict, List, Optional
import shutil
import random

def load_transforms_json(transforms_path: str) -> Dict:
    """Load camera transforms from JSON file generated by Blender renderer."""
    with open(transforms_path, 'r') as f:
        data = json.load(f)
    return data

PRIMES = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]

def radical_inverse(base, n):
    val = 0
    inv_base = 1.0 / base
    inv_base_n = inv_base
    while n > 0:
        digit = n % base
        val += digit * inv_base_n
        n //= base
        inv_base_n *= inv_base
    return val

def halton_sequence(dim, n):
    return [radical_inverse(PRIMES[dim], n) for dim in range(dim)]

def hammersley_sequence(dim, n, num_samples):
    return [n / num_samples] + halton_sequence(dim - 1, n)

def sphere_hammersley_sequence(n, num_samples, offset=(0, 0)):
    u, v = hammersley_sequence(2, n, num_samples)
    u += offset[0] / num_samples
    v += offset[1]
    u = 2 * u if u < 0.25 else 2 / 3 * u + 1 / 3
    theta = np.arccos(1 - 2 * u) - np.pi / 2
    phi = v * 2 * np.pi
    return [phi, theta]

def hammersley_sphere_cameras(n_views: int, radius: float, camera_angle_x: float, up_dir: str = 'z') -> List[Dict]:
    """Generate camera poses uniformly distributed on a sphere using Hammersley sequence.
    
    Args:
        n_views: Number of camera views to generate
        radius: Distance from origin to camera
        camera_angle_x: Horizontal field of view in radians
        up_dir: Up direction ('z' or 'y')
        
    Returns:
        List of frame dictionaries with camera parameters
    """
    # Generate Hammersley sequence
    offset = (np.random.rand(), np.random.rand())
    
    frames = []
    for i in range(n_views):
        # Convert Hammersley samples to spherical coordinates
        # theta: azimuth angle [0, 2*pi]
        # phi: elevation angle [0, pi]
        phi, theta = sphere_hammersley_sequence(i, n_views, offset)
        
        # Convert spherical to Cartesian coordinates
        x = radius * np.cos(phi) * np.cos(theta)
        y = radius * np.sin(phi) * np.cos(theta)
        z = radius * np.sin(theta)
        
        camera_pos = np.array([x, y, z])
        
        # Camera looks at origin
        look_at = np.array([0., 0., 0.])
        
        # Set up vector based on up_dir
        if up_dir == 'z':
            world_up = np.array([0., 0., 1.])
        else:
            world_up = np.array([0., 1., 0.])
        
        # Compute camera coordinate frame
        forward = look_at - camera_pos
        forward = forward / np.linalg.norm(forward)
        
        right = np.cross(forward, world_up)
        right = right / np.linalg.norm(right)
        
        up = np.cross(right, forward)
        up = up / np.linalg.norm(up)
        
        # Build 4x4 camera-to-world transform matrix
        # Blender coordinate system: 
        # - Camera local axes: +X right, +Y up, +Z backward (looks along -Z)
        # - World space: +X right, +Y forward, +Z up
        # Transform matrix columns represent camera's local axes in world coordinates
        transform_matrix = np.eye(4)
        transform_matrix[:3, 0] = right      # Camera X-axis (right) in world coords
        transform_matrix[:3, 1] = up         # Camera Y-axis (up) in world coords
        transform_matrix[:3, 2] = -forward   # Camera Z-axis (backward) in world coords
        transform_matrix[:3, 3] = camera_pos # Camera position in world coords
        
        frame = {
            "file_path": f"{i:03d}.png",
            "camera_angle_x": camera_angle_x,
            "transform_matrix": transform_matrix.tolist()
        }
        
        frames.append(frame)
    
    return frames

def load_mesh_with_textures(mesh_path: str, flip_uv_u: bool = False, flip_uv_v: bool = False) -> Tuple[torch.Tensor, torch.Tensor, Optional[torch.Tensor], Optional[torch.Tensor], Optional[torch.Tensor]]:
    """Load mesh from file and return vertices, faces, UV coordinates, texture, and vertex colors as tensors.
    
    Args:
        mesh_path: Path to mesh file (supports .obj, .ply, .glb, etc.)
        flip_uv_u: Flip U coordinates (horizontal flip)
        flip_uv_v: Flip V coordinates (vertical flip)
        
    Returns:
        vertices: Tensor of shape (V, 3)
        faces: Tensor of shape (F, 3) with vertex indices
        uv_coords: Tensor of shape (V, 2) or None if no UV coordinates
        texture: Tensor of shape (H, W, 3) or None if no texture
        vertex_colors: Tensor of shape (V, 3) or None if no vertex colors (fallback)
    """    
    # Load the full scene to access materials and textures
    scene = trimesh.load(mesh_path)
    
    # Handle different loading results
    if isinstance(scene, trimesh.Scene):
        # Get all meshes from the scene
        meshes = [geometry for geometry in scene.geometry.values() if isinstance(geometry, trimesh.Trimesh)]
        if not meshes:
            raise ValueError("No mesh found in the scene")
        
        if len(meshes) > 1:
            # Concatenate all meshes into a single mesh
            # This preserves vertex colors and textures where possible
            print(f"Found {len(meshes)} meshes in scene, merging them...")
            mesh = trimesh.util.concatenate(meshes)
        else:
            mesh = meshes[0]  # Use the first mesh
    else:
        # Single mesh case
        mesh = scene

    vertices = mesh.vertices.copy()

    # only apply normalization to GSO, for shapenet, directly scale down
    if 'shapenetcorev2' not in mesh_path.lower():
        xmin, xmax = float(vertices[:, 0].min()), float(vertices[:, 0].max())
        ymin, ymax = float(vertices[:, 1].min()), float(vertices[:, 1].max())
        zmin, zmax = float(vertices[:, 2].min()), float(vertices[:, 2].max())
        scale = max(max(xmax - xmin, ymax - ymin), zmax - zmin) / 2.0

        vertices[:, 0] -= (xmax + xmin) / 2.0
        vertices[:, 1] -= (ymax + ymin) / 2.0
        vertices[:, 2] -= (zmax + zmin) / 2.0
        vertices[:, :3] /= scale 
    vertices[:, :3] *= 0.1

    mesh.vertices = vertices
    
    # Extract texture from mesh's PBR material
    texture_image = None
    
    # Check mesh visual material for PBR textures
    if hasattr(mesh.visual, 'material') and mesh.visual.material is not None:
        material = mesh.visual.material
        
        # Check for PBR material baseColorTexture
        if hasattr(material, 'baseColorTexture') and material.baseColorTexture is not None:
            texture_image = material.baseColorTexture
            print(f"Found PBR base color texture in mesh material")
        # Check for standard image attribute  
        elif hasattr(material, 'image') and material.image is not None:
            texture_image = material.image
            print(f"Found texture image in mesh material")
        # Check for main_color (sometimes used in trimesh)
        elif hasattr(material, 'main_color') and hasattr(material.main_color, 'texture'):
            texture_image = material.main_color.texture
            print(f"Found main color texture in mesh material")
    
    # Fallback: check scene-level materials if mesh material didn't work
    if texture_image is None and isinstance(scene, trimesh.Scene):
        if hasattr(scene, 'materials') and scene.materials:
            # Get the first material from scene
            scene_material = list(scene.materials.values())[0]
            
            if hasattr(scene_material, 'baseColorTexture') and scene_material.baseColorTexture is not None:
                texture_image = scene_material.baseColorTexture
                print(f"Found PBR base color texture in scene material")
            elif hasattr(scene_material, 'image') and scene_material.image is not None:
                texture_image = scene_material.image
                print(f"Found texture image in scene material")
        
        # Also check if the scene has texture images stored elsewhere
        if texture_image is None and hasattr(scene, 'images') and scene.images:
            texture_image = list(scene.images.values())[0]
            print(f"Found texture in scene images")
    
    # Convert mesh data to tensors
    # print(f"Raw mesh vertices shape: {mesh.vertices.shape}")
    # print(f"Raw mesh faces shape: {mesh.faces.shape}")
    
    vertices = torch.from_numpy(mesh.vertices).float()
    faces = torch.from_numpy(mesh.faces).int()  # nvdiffrast requires int32 tensors
    
    # Extract UV coordinates
    uv_coords = None
    if hasattr(mesh.visual, 'uv') and mesh.visual.uv is not None:
        uv_coords = torch.from_numpy(mesh.visual.uv).float()
        print(f"Loaded UV coordinates: {uv_coords.shape}")
        
        # Apply UV coordinate flipping if requested
        if flip_uv_u:
            uv_coords[:, 0] = 1.0 - uv_coords[:, 0]
            print("Applied U coordinate flip")
        if flip_uv_v:
            uv_coords[:, 1] = 1.0 - uv_coords[:, 1]
            print("Applied V coordinate flip")
        
        # Check if UV coordinates need to match face vertices
        if uv_coords.shape[0] != vertices.shape[0]:
            print(f"Warning: UV coords ({uv_coords.shape[0]}) don't match vertices ({vertices.shape[0]})")
            # Try to handle face-based UV coordinates if available
            if hasattr(mesh, 'faces_tex') and mesh.faces_tex is not None:
                print("Found per-face UV indices, attempting to map to vertices")
                # This is more complex and would need proper face-vertex UV mapping
                # For now, we'll proceed with available UV coords
    else:
        print("No UV coordinates found in mesh")
    
    # Process texture image
    texture = None
    if texture_image is not None:
        try:
            # Convert PIL image to tensor
            if hasattr(texture_image, 'size'):  # PIL Image
                texture_np = np.array(texture_image)
            else:  # Already numpy array
                texture_np = texture_image
                
            if len(texture_np.shape) == 3 and texture_np.shape[2] >= 3:
                # Convert to RGB if RGBA
                texture = torch.from_numpy(texture_np[:, :, :3]).float() / 255.0
                print(f"Loaded texture: {texture.shape}")
            else:
                print(f"Warning: Texture has unexpected shape: {texture_np.shape}")
        except Exception as e:
            print(f"Warning: Failed to process texture: {e}")
    else:
        print("No texture found in mesh")
    
    # Extract vertex colors as fallback or convert from texture
    vertex_colors = None
    
    # First check if mesh already has vertex colors
    if hasattr(mesh.visual, 'material'):
        colors = mesh.visual.material.to_color(uv=np.clip(mesh.visual.uv, 0, 1 - 1e-6))
        if colors.shape[1] >= 3:
            vertex_colors = torch.from_numpy(colors[:, :3]).float() / 255.0
            print(f"Loaded existing vertex colors: {vertex_colors.shape}")
    elif hasattr(mesh.visual, 'face_colors') and mesh.visual.face_colors is not None:
        # Convert face colors to vertex colors
        face_colors = mesh.visual.face_colors
        if face_colors.shape[1] >= 3:
            vertex_colors = torch.zeros(vertices.shape[0], 3)
            vertex_count = torch.zeros(vertices.shape[0])
            
            face_colors_tensor = torch.from_numpy(face_colors[:, :3]).float() / 255.0
            for i, face in enumerate(faces):
                for vertex_idx in face:
                    vertex_colors[vertex_idx] += face_colors_tensor[i]
                    vertex_count[vertex_idx] += 1
            
            valid_vertices = vertex_count > 0
            vertex_colors[valid_vertices] /= vertex_count[valid_vertices].unsqueeze(1)
            vertex_colors = vertex_colors.float()
            print(f"Converted face colors to vertex colors: {vertex_colors.shape}")
    else:
        print("No vertex colors, face colors, or texture+UV found in mesh")
    
    return vertices, faces, uv_coords, texture, vertex_colors

def normalize_mesh(vertices: torch.Tensor, scale: float, offset: List[float]) -> torch.Tensor:
    """Normalize mesh to match Blender normalization.
    
    Args:
        vertices: Mesh vertices
        scale: Scale factor from transforms.json
        offset: Offset from transforms.json
        
    Returns:
        Normalized vertices
    """
    # Apply the same normalization as Blender
    vertices = vertices * scale
    vertices = vertices + torch.tensor(offset, dtype=vertices.dtype, device=vertices.device)
    return vertices

def find_subfolder_pairs(save_transforms_root: str, mesh_root: str) -> List[Tuple[str, str, str]]:
    """Find matching subfolder pairs containing transforms.json and mesh files.
    
    Args:
        transforms_root: Root directory containing subfolders with transforms.json
        mesh_root: Root directory containing subfolders with mesh files
        
    Returns:
        List of tuples (subfolder_name, transforms_path, mesh_path)
    """
    pairs = []
    
    for subfolder in os.listdir(mesh_root):
        mesh_subfolder = os.path.join(mesh_root, subfolder, 'meshes')
        
        # Check if both subfolders exist
        if not os.path.exists(mesh_subfolder) or not os.path.isdir(mesh_subfolder):
            print(f"Warning: Mesh subfolder does not exist: {mesh_subfolder}")
            continue
            
        # Check for transforms.json
        transforms_path = os.path.join(save_transforms_root, subfolder, 'transforms.json')
            
        # Find mesh file (OBJ format)
        mesh_files = []
        for ext in ['*.obj']:
            mesh_files.extend([f for f in os.listdir(mesh_subfolder) if f.lower().endswith('.obj')])
        
        if not mesh_files:
            print(f"Warning: No OBJ mesh files found in {mesh_subfolder}")
            continue
            
        # Use the first OBJ file found
        mesh_path = os.path.join(mesh_subfolder, mesh_files[0])
        
        pairs.append((subfolder, transforms_path, mesh_path))
        
    return pairs

def find_subfolder_pairs_shapenet(save_transforms_root: str, mesh_root: str) -> List[Tuple[str, str, str]]:
    """Find matching subfolder pairs containing transforms.json and mesh files.
    
    Args:
        transforms_root: Root directory containing subfolders with transforms.json
        mesh_root: Root directory containing subfolders with mesh files
        
    Returns:
        List of tuples (subfolder_name, transforms_path, mesh_path)
    """
    pairs = []
    
    for subfolder in os.listdir(mesh_root):
        if not os.path.isdir(os.path.join(mesh_root, subfolder)):
            continue
        for subsubfolder in os.listdir(os.path.join(mesh_root, subfolder)):
            mesh_subfolder = os.path.join(mesh_root, subfolder, subsubfolder, 'models')
            
            # Check if both subfolders exist
            if not os.path.exists(mesh_subfolder) or not os.path.isdir(mesh_subfolder):
                print(f"Warning: Mesh subfolder does not exist: {mesh_subfolder}")
                continue
                
            # Check for transforms.json
            transforms_path = os.path.join(save_transforms_root, subfolder, subsubfolder, 'transforms.json')
                
            # Find mesh file (OBJ format)
            mesh_files = []
            for ext in ['*.obj']:
                mesh_files.extend([f for f in os.listdir(mesh_subfolder) if f.lower().endswith('.obj')])
            
            if not mesh_files:
                print(f"Warning: No OBJ mesh files found in {mesh_subfolder}")
                continue
                
            # Use the first OBJ file found
            mesh_path = os.path.join(mesh_subfolder, mesh_files[0])
            
            pairs.append((os.path.join(subfolder, subsubfolder), transforms_path, mesh_path))
        
    return pairs

def blender_to_opencv_camera_matrix(transform_matrix: List[List[float]], fov_x, image_width=1, image_height=1) -> torch.Tensor:
    """Convert Blender camera transform matrix to OpenCV format.
    
    Blender uses a different coordinate system than OpenCV:
    - Blender: +X right, +Y forward, +Z up
    - OpenCV: +X right, +Y down, +Z forward
    
    Args:
        transform_matrix: 4x4 camera transform matrix from Blender
        
    Returns:
        4x4 camera matrix in OpenCV format
    """

    focal_length = image_width / (2.0 * np.tan(fov_x / 2.0))
    
    # Construct intrinsic matrix (assuming principal point at image center)
    intrinsics = np.array([
        [focal_length, 0, image_width / 2.0],
        [0, focal_length, image_height / 2.0],
        [0, 0, 1]
    ])

    # Convert to tensor - this is camera-to-world matrix from Blender
    cam_to_world = torch.tensor(transform_matrix, dtype=torch.float32)
    
    # Object coordinate system transformation: Z-up to Y-up
    # The transformation matrix assumes Z-up objects, but our object is Y-up
    # Rotation: X->X, Y->Z, Z->-Y (90 degree rotation around X axis)
    z_up_to_y_up = torch.tensor([
        [1,  0,  0,  0],
        [0,  0,  1,  0],  # Y <- Z
        [0, -1,  0,  0],  # Z <- -Y
        [0,  0,  0,  1]
    ], dtype=torch.float32)
    
    # Blender to OpenCV coordinate system conversion
    # Blender: +X right, +Y forward, +Z up
    # OpenCV: +X right, +Y down, +Z forward
    blender_to_opencv = torch.tensor([
        [1,  0,  0,  0],
        [0, -1,  0,  0],  # Y axis flipped
        [0,  0, -1,  0],  # Z axis flipped  
        [0,  0,  0,  1]
    ], dtype=torch.float32)
    
    # Apply transformations in the correct order:
    # 1. First apply object coordinate transformation (Z-up to Y-up)
    # 2. Then apply camera coordinate system conversion (Blender to OpenCV)
    
    # 1) The last z_up_to_y_up.inverse() is because geometry itself has a rotation (Note for scene transform and obj transform). 2) Since cam_to_world.inverse() @ z_up_to_y_up.inverse() @ z_up_to_y_up.inverse() has projected 3D points to camera coordinate, there is no need for an additional z_up_to_y_up.
    cam_to_world_corrected = blender_to_opencv @ cam_to_world.inverse() #@ z_up_to_y_up.inverse() @ z_up_to_y_up.inverse()

    # For rendering, we need the view matrix (world-to-camera)
    view_matrix = cam_to_world_corrected

    return torch.from_numpy(intrinsics).float(), view_matrix

def intrinsics_to_projection(
        intrinsics: torch.Tensor,
        near: float = 0.1,
        far: float = 1000.0,
    ) -> torch.Tensor:
    """
    OpenCV intrinsics to OpenGL perspective matrix

    Args:
        intrinsics (torch.Tensor): [3, 3] OpenCV intrinsics matrix
        near (float): near plane to clip
        far (float): far plane to clip
    Returns:
        (torch.Tensor): [4, 4] OpenGL perspective matrix
    """
    fx, fy = intrinsics[0, 0], intrinsics[1, 1]
    cx, cy = intrinsics[0, 2], intrinsics[1, 2]
    ret = torch.zeros((4, 4), dtype=intrinsics.dtype, device=intrinsics.device)
    ret[0, 0] = 2 * fx
    ret[1, 1] = 2 * fy
    ret[0, 2] = 2 * cx - 1
    ret[1, 2] = - 2 * cy + 1
    ret[2, 2] = far / (far - near)
    ret[2, 3] = near * far / (near - far)
    ret[3, 2] = 1.
    return ret

def sample_texture(uv_coords: torch.Tensor, texture: torch.Tensor, device: str = 'cuda') -> torch.Tensor:
    """Sample texture using UV coordinates with bilinear interpolation.
    
    Args:
        uv_coords: UV coordinates tensor of shape (V, 2)
        texture: Texture tensor of shape (H, W, 3)
        device: Device to run on
        
    Returns:
        colors: Sampled colors tensor of shape (V, 3)
    """
    import torch.nn.functional as F
    
    uv_coords = uv_coords.to(device)
    texture = texture.to(device)
    
    # Convert UV coordinates from [0,1] to [-1,1] for grid_sample
    # Also flip V coordinate because texture V=0 is top, but UV V=0 is bottom
    grid_uv = uv_coords * 2.0 - 1.0
    grid_uv[:, 1] = -grid_uv[:, 1]  # Flip V coordinate
    
    # Add batch and "height" dimensions for grid_sample
    # grid_sample expects (N, H_out, W_out, 2), we have (V, 2)
    grid = grid_uv.unsqueeze(0).unsqueeze(0)  # (1, 1, V, 2)
    
    # Add batch dimension to texture and permute to (N, C, H, W) format
    texture_batch = texture.permute(2, 0, 1).unsqueeze(0)  # (1, 3, H, W)
    
    # Sample texture
    sampled = F.grid_sample(texture_batch, grid, mode='bilinear', 
                          padding_mode='border', align_corners=False)  # (1, 3, 1, V)
    
    # Remove extra dimensions and permute back to (V, 3)
    colors = sampled.squeeze(0).squeeze(1).permute(1, 0)  # (V, 3)
    
    return colors

def render_mesh(
    vertices: torch.Tensor,
    faces: torch.Tensor,
    camera_matrix: torch.Tensor,
    projection_matrix: torch.Tensor,
    uv_coords: Optional[torch.Tensor] = None,
    texture: Optional[torch.Tensor] = None,
    vertex_colors: Optional[torch.Tensor] = None,
    shading_mode: str = 'texture',
    resolution: int = 512,
    device: str = 'cuda',
    ssaa_factor: int = 2,
    ssaa_filter: str = 'bilinear'
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Render mesh using nvdiffrast with texture mapping, vertex colors, or normal-based shading.
    
    Args:
        vertices: Mesh vertices (V, 3)
        faces: Mesh faces (F, 3)
        camera_matrix: Camera transform matrix (4, 4)
        projection_matrix: Projection matrix (4, 4)
        uv_coords: Optional UV coordinates (V, 2)
        texture: Optional texture image (H, W, 3)
        vertex_colors: Optional vertex colors (V, 3)
        shading_mode: 'texture', 'vertex_color', 'normal', or 'random'
        resolution: Target image resolution (final output size)
        device: Device to run on
        ssaa_factor: SSAA factor - render at (resolution * ssaa_factor) then downsample
        ssaa_filter: Downsampling filter for SSAA ('bilinear', 'area', 'lanczos')
        
    Returns:
        rgb_image: Rendered RGB image (H, W, 3)
        depth_image: Rendered depth image (H, W)
    """
    # Debug: Check input shapes
    # print(f"Input vertices shape: {vertices.shape}")
    # print(f"Input faces shape: {faces.shape}")
    
    # Validate inputs
    if vertices.shape[0] == 0:
        raise ValueError("Mesh has no vertices")
    if faces.shape[0] == 0:
        raise ValueError("Mesh has no faces")
    if faces.shape[1] != 3:
        raise ValueError(f"Faces must have 3 vertices per face, got {faces.shape[1]}")
    
    # Move to device and ensure correct dtypes for nvdiffrast
    vertices = vertices.to(device)
    faces = faces.to(device).int()  # nvdiffrast requires int32 tensors
    camera_matrix = camera_matrix.to(device)
    projection_matrix = projection_matrix.to(device)
    
    # Add batch dimension
    vertices = vertices.unsqueeze(0)  # (1, V, 3)
    faces = faces.unsqueeze(0)  # (1, F, 3)
    
    # print(f"After processing - vertices shape: {vertices.shape}, faces shape: {faces.shape}")
    
    # Convert vertices to homogeneous coordinates
    vertices_homo = torch.cat([vertices, torch.ones_like(vertices[..., :1])], dim=-1)  # (1, V, 4)
    
    # Transform vertices to camera space using the view matrix (world-to-camera)
    # camera_matrix is already the view matrix from blender_to_opencv_camera_matrix
    view_matrix = camera_matrix
    vertices_cam = torch.matmul(vertices_homo, view_matrix.T)  # (1, V, 4)
    
    # Project to clip space
    vertices_clip = torch.matmul(vertices_cam, projection_matrix.T)  # (1, V, 4)

    # invert z and y
    # vertices_clip[..., 1] = -vertices_clip[..., 1]
    # vertices_clip[..., 2] = -vertices_clip[..., 2]

    # Determine color source and prepare colors based on shading mode and availability
    use_texture_sampling = False
    if shading_mode == 'texture' and uv_coords is not None and texture is not None:
        # Use dr.texture for texture mapping (highest priority when requested)
        use_texture_sampling = True
        # Prepare UV coordinates for interpolation
        uv_coords = uv_coords.to(device)
        
        # Ensure UV coordinates are in [0,1] range and handle potential flipping
        uv_coords = torch.clamp(uv_coords, 0.0, 1.0)
        
        # Check if we need to flip V coordinate based on texture orientation
        # Most 3D formats have V=0 at bottom, but image textures have V=0 at top
        # We'll provide both orientations and let the user choose
        colors = uv_coords.unsqueeze(0)  # (1, V, 2) - UV coordinates to be interpolated
        # print("Using dr.texture for UV texture mapping")
    elif shading_mode == 'vertex_color' and vertex_colors is not None:
        # Use vertex colors
        vertex_colors = vertex_colors.to(device)
        colors = vertex_colors.unsqueeze(0)  # (1, V, 3)
        colors = torch.cat([colors, torch.ones(1, colors.shape[1], 1, device=device)], dim=-1)  # Add alpha
        # print("Using vertex colors for rendering")
    elif shading_mode == 'normal':
        # Use vertex normal-based shading with world-space normals (camera viewpoint invariant)
        # First compute face normals
        face_vertices = vertices[0, faces[0]]  # (F, 3, 3)
        v0, v1, v2 = face_vertices[:, 0], face_vertices[:, 1], face_vertices[:, 2]
        face_normals = torch.cross(v1 - v0, v2 - v0, dim=1)
        face_normals = torch.nn.functional.normalize(face_normals, p=2, dim=1)
        
        # Compute vertex normals by averaging adjacent face normals using scatter_add
        num_vertices = vertices.shape[1]
        vertex_normals = torch.zeros(num_vertices, 3, device=device)
        vertex_count = torch.zeros(num_vertices, device=device)
        
        # Prepare indices and values for scatter_add
        # Each face contributes to 3 vertices, so we replicate face normals 3 times
        face_indices = faces[0].flatten().long()  # (F*3,) - vertex indices from all faces, convert to int64
        face_normals_expanded = face_normals.repeat_interleave(3, dim=0)  # (F*3, 3) - replicate each face normal 3 times
        
        # Accumulate face normals to vertices using scatter_add
        vertex_normals.scatter_add_(0, face_indices.unsqueeze(1).expand(-1, 3), face_normals_expanded)
        vertex_count.scatter_add_(0, face_indices, torch.ones_like(face_indices, dtype=torch.float32))
        
        # Average and normalize vertex normals
        valid_vertices = vertex_count > 0
        vertex_normals[valid_vertices] /= vertex_count[valid_vertices].unsqueeze(1)
        vertex_normals = torch.nn.functional.normalize(vertex_normals, p=2, dim=1)
        
        # Use world-space vertex normals directly - map XYZ components to RGB
        # Normalize from [-1, 1] to [0, 1] range for color representation
        vertex_colors_rgb = (vertex_normals + 1.0) * 0.5  # Map [-1,1] to [0,1]
        vertex_colors_rgb = torch.clamp(vertex_colors_rgb, 0.0, 1.0)  # Ensure valid color range
        
        # Add batch dimension and alpha channel
        vertex_colors = vertex_colors_rgb.unsqueeze(0)  # Add batch dimension
        colors = torch.cat([vertex_colors, torch.ones(1, vertex_colors.shape[1], 1, device=device)], dim=-1)  # Add alpha
        print("Using world-space vertex normal-based coloring (camera viewpoint invariant)")
    elif shading_mode == 'random':
        # Use random colors per face
        num_faces = faces.shape[1]
        face_colors = torch.rand(1, num_faces, 3, device=device)
        face_colors = torch.cat([face_colors, torch.ones(1, num_faces, 1, device=device)], dim=-1)
        colors = face_colors
        print("Using random face colors")
    else:
        raise ValueError(f"Unknown shading mode: {shading_mode}")

    # Create rendering context
    glctx = dr.RasterizeGLContext()
    
    # Calculate render resolution for SSAA
    render_resolution = resolution * ssaa_factor
    
    # Rasterize at higher resolution for SSAA
    rast_out, rast_db = dr.rasterize(glctx, vertices_clip, faces[0], resolution=[render_resolution, render_resolution], grad_db=True)
    
    # Get depth and triangle ID
    depth = rast_out[..., 2:3]  # (1, H, W, 1)
    triangle_id = rast_out[..., 3:4]  # (1, H, W, 1)
    
    # Interpolate colors or UV coordinates based on shading mode
    if use_texture_sampling:
        # Interpolate UV coordinates
        uv_interpolated, uv_dr = dr.interpolate(colors, rast_out, faces[0], rast_db, diff_attrs='all')  # (1, H, W, 2)
        
        # Sample texture using dr.texture
        texture = texture.to(device)
        # Ensure texture has the right format (H, W, C) and add batch dimension if needed
        if len(texture.shape) == 3:
            texture_batch = texture.unsqueeze(0)  # (1, H, W, C)
        else:
            texture_batch = texture
        
        # Use dr.texture to sample the texture
        rgb_image = dr.texture(texture_batch, uv_interpolated, uv_dr)  # (1, H, W, C)
    else:
        # Interpolate colors directly
        rgb_image, _ = dr.interpolate(colors, rast_out, faces[0])

    # Anti-aliasing (nvdiffrast's built-in AA)
    if use_texture_sampling:
        # For texture sampling, we need to handle the alpha channel properly
        rgb_image = dr.antialias(rgb_image, rast_out, vertices_clip, faces[0])

        mask = dr.antialias((rast_out[..., -1:] > 0).float(), rast_out, vertices_clip, faces[0])
        rgb_image = torch.where(mask > 0, rgb_image, torch.zeros_like(rgb_image))

        # add alpha
        rgb_image = torch.cat([rgb_image, torch.ones_like(rgb_image[..., :1])], dim=-1)
    else:
        rgb_image = dr.antialias(rgb_image, rast_out, vertices_clip, faces[0])

    # Handle background (where triangle_id == 0)
    background_mask = (triangle_id == 0).squeeze(-1)  # (1, H, W)
    rgb_image = rgb_image.squeeze(0)  # (H, W, 4)
    rgb_image[background_mask.squeeze(0)] = torch.tensor([0.0, 0.0, 0.0, 0.0], device=device)  # Black background

    # Extract depth and handle background
    depth_image = depth.squeeze()  # (H, W)
    depth_image[background_mask.squeeze(0)] = 0.0  # Set background depth to 0
    
    # Apply SSAA downsampling if needed
    if ssaa_factor > 1:
        # Import here to avoid overhead when not using SSAA
        import torch.nn.functional as F
        
        # Downsample RGB image
        rgb_for_downsample = rgb_image[..., :3].permute(2, 0, 1).unsqueeze(0)  # (1, 3, H, W)
        
        if ssaa_filter == 'bilinear':
            rgb_downsampled = F.interpolate(rgb_for_downsample, size=(resolution, resolution), 
                                          mode='bilinear', align_corners=False)
        elif ssaa_filter == 'area':
            rgb_downsampled = F.interpolate(rgb_for_downsample, size=(resolution, resolution), 
                                          mode='area')
        elif ssaa_filter == 'lanczos':
            # PyTorch doesn't have native Lanczos, use area as fallback
            rgb_downsampled = F.interpolate(rgb_for_downsample, size=(resolution, resolution), 
                                          mode='area')
        else:
            # Default to bilinear
            rgb_downsampled = F.interpolate(rgb_for_downsample, size=(resolution, resolution), 
                                          mode='bilinear', align_corners=False)
        
        rgb_image = rgb_downsampled.squeeze(0).permute(1, 2, 0)  # (H, W, 3)
        
        # Downsample depth image
        depth_for_downsample = depth_image.unsqueeze(0).unsqueeze(0)  # (1, 1, H, W)
        depth_downsampled = F.interpolate(depth_for_downsample, size=(resolution, resolution), 
                                        mode='bilinear', align_corners=False)
        depth_image = depth_downsampled.squeeze(0).squeeze(0)  # (H, W)
        
        # if ssaa_factor > 1:
        #     print(f"Applied SSAA {ssaa_factor}x with {ssaa_filter} filtering")
    
    return rgb_image, depth_image

def save_image(image: torch.Tensor, filepath: str):
    """Save tensor image to file."""
    # Convert to numpy and scale to 0-255
    image_np = (image.detach().cpu().numpy() * 255).astype(np.uint8)
    
    # Convert to PIL and save
    image_pil = Image.fromarray(image_np)
    image_pil.save(filepath)

def save_depth(depth: torch.Tensor, filepath: str, near: float = 0.1, far: float = 100.0) -> Tuple[float, float]:
    """Save depth tensor to file as PNG with normalization.
    
    Args:
        depth: Depth tensor
        filepath: Output file path
        near: Near clipping plane (unused)
        far: Far clipping plane (unused)
        
    Returns:
        Tuple of (min_depth, max_depth) for the valid depth values
    """
    # Convert to numpy
    depth_np = depth.detach().cpu().numpy()
    
    # Handle background (depth == 0)
    valid_mask = depth_np > 0
    if valid_mask.any():
        # Get min and max of valid depths
        min_depth = float(depth_np[valid_mask].min())
        max_depth = float(depth_np[valid_mask].max())
        
        if max_depth > min_depth:
            # Normalize: (depth - min) / (max - min)
            depth_normalized = np.zeros_like(depth_np)
            depth_normalized[valid_mask] = (depth_np[valid_mask] - min_depth) / (max_depth - min_depth)
        else:
            depth_normalized = np.zeros_like(depth_np)
    else:
        # No valid depth values
        min_depth = 0.0
        max_depth = 0.0
        depth_normalized = np.zeros_like(depth_np)
    
    # Convert to 16-bit unsigned integer for better precision
    depth_uint16 = (depth_normalized * 65535).astype(np.uint16)
    
    # Save using OpenCV
    cv2.imwrite(filepath, depth_uint16)
    
    return min_depth, max_depth

def save_vertices_as_ply(vertices: torch.Tensor, faces: torch.Tensor, vertex_colors: Optional[torch.Tensor], filepath: str):
    """Save vertices and faces as PLY file for debugging.
    
    Args:
        vertices: Mesh vertices (V, 3)
        faces: Mesh faces (F, 3)
        vertex_colors: Optional vertex colors (V, 3)
        filepath: Output PLY file path
    """
    # Convert tensors to numpy
    vertices_np = vertices.detach().cpu().numpy()
    faces_np = faces.detach().cpu().numpy()
    
    # Create trimesh object
    mesh = trimesh.Trimesh(vertices=vertices_np, faces=faces_np)
    
    # Add vertex colors if available
    if vertex_colors is not None:
        colors_np = vertex_colors.detach().cpu().numpy()
        # Convert to 0-255 range and ensure uint8
        colors_uint8 = (colors_np * 255).astype(np.uint8)
        mesh.visual.vertex_colors = colors_uint8
    
    # Save as PLY
    mesh.export(filepath)

def process_subfolder_pair(subfolder_name: str, transforms_path: str, mesh_path: str, args) -> None:
    """Process a single subfolder pair for rendering.
    
    Args:
        subfolder_name: Name of the subfolder
        transforms_path: Path to transforms.json file (will be created or read)
        mesh_path: Path to mesh file
        args: Command line arguments
        
    Returns:
        None
    """
    print(f"\n{'='*60}")
    print(f"Processing subfolder: {subfolder_name}")
    print(f"  Mesh: {mesh_path}")
    
    # Create output directory for this subfolder
    output_dir = os.path.join(args.output_root, subfolder_name)
    os.makedirs(output_dir, exist_ok=True)

    # Load mesh with textures and colors
    print(f"Loading mesh from {mesh_path}")
    vertices, faces, uv_coords, texture, vertex_colors = load_mesh_with_textures(mesh_path, args.flip_uv_u, args.flip_uv_v)
    print(f"Loaded mesh with {vertices.shape[0]} vertices and {faces.shape[0]} faces")

    # save vertices as ply for debug
    # debug_ply_path = os.path.join(output_dir, f"{subfolder_name}_debug.ply")
    # save_vertices_as_ply(vertices, faces, vertex_colors, debug_ply_path)
    # print(f"Saved debug PLY to {debug_ply_path}")
    
    # Check if we should read transforms from source folder instead of generating them
    # This is used when rendering normal maps from pre-computed transforms
    if args.shading_mode == 'normal' and 'renders3-normal' in args.output_root:
        # Try to read transforms from the color render folder
        source_output_root = args.output_root.replace('renders3-normal', 'renders3-color')
        transforms_source_path = os.path.join(source_output_root, subfolder_name, 'transforms.json')
        
        if not os.path.exists(transforms_source_path):
            raise FileNotFoundError(f"Source transforms not found at {transforms_source_path}. Required when rendering normal maps.")
        
        print(f"Loading camera transforms from {transforms_source_path}")
        with open(transforms_source_path, 'r') as f:
            transforms_data = json.load(f)
        print(f"Loaded camera transforms with {len(transforms_data['frames'])} frames")
    else:
        # Generate camera transforms using Hammersley sequence
        print(f"Generating {args.n_views} camera views using Hammersley sequence...")
        frames = hammersley_sphere_cameras(
            n_views=args.n_views,
            radius=args.camera_radius,
            camera_angle_x=args.camera_angle_x,
            up_dir='z'
        )
        
        # Create transforms data structure
        transforms_data = {
            "camera_angle_x": args.camera_angle_x,
            "frames": frames,
            "scale": 1.0,
            "offset": [0.0, 0.0, 0.0]
        }
        
        # Save transforms.json to output directory
        transforms_output_path = os.path.join(output_dir, 'transforms.json')
        with open(transforms_output_path, 'w') as f:
            json.dump(transforms_data, f, indent=4)
        print(f"Saved camera transforms to {transforms_output_path}")
    
    # Normalize mesh to match Blender normalization (unless skipped)
    if not args.skip_normalization:
        vertices = normalize_mesh(vertices, transforms_data['scale'], transforms_data['offset'])
        print(f"Applied normalization: scale={transforms_data['scale']}, offset={transforms_data['offset']}")
    else:
        print("Skipping mesh normalization")
    
    # Get aspect ratio
    aspect_ratio = 1.0  # Assuming square images
    
    print(f"Rendering {len(transforms_data['frames'])} views...")
    
    # Render each view
    for i, frame in enumerate(transforms_data['frames']):
        if i % 10 == 0:  # Progress indicator
            print(f"  Rendering view {i:03d}/{len(transforms_data['frames'])}")
        
        # Get camera parameters
        fov_x = frame['camera_angle_x']
        transform_matrix = frame['transform_matrix']
        
        # Get output filename from frame data
        file_path = frame.get('file_path', f'{i:03d}.png')
        # Remove extension and get base name
        base_name = os.path.splitext(file_path)[0]
        
        # Convert camera matrix
        intrinsic, camera_matrix = blender_to_opencv_camera_matrix(transform_matrix, fov_x)

        # Create projection matrix
        projection_matrix = intrinsics_to_projection(intrinsic, args.near, args.far)

        # Render using the consolidated function
        rgb_image, depth_image = render_mesh(
            vertices, faces, camera_matrix, projection_matrix,
            uv_coords, texture, vertex_colors, args.shading_mode,
            args.resolution, args.device, args.ssaa_factor, args.ssaa_filter
        )
        
        # Save RGB image using file_path from transforms.json
        rgb_path = os.path.join(output_dir, file_path)
        # Ensure the directory exists for the file path
        rgb_dir = os.path.dirname(rgb_path)
        if rgb_dir and rgb_dir != output_dir:
            os.makedirs(rgb_dir, exist_ok=True)
        save_image(rgb_image, rgb_path)
        
        # Save depth if requested and update frame with depth info
        if args.save_depth:
            # Create depth filename by adding _depth suffix
            depth_filename = base_name + '_depth.png'
            depth_path = os.path.join(output_dir, depth_filename)
            depth_dir = os.path.dirname(depth_path)
            if depth_dir and depth_dir != output_dir:
                os.makedirs(depth_dir, exist_ok=True)
            min_depth, max_depth = save_depth(depth_image, depth_path, args.near, args.far)
            
            # Add depth min/max to frame data
            frame['depth'] = {
                'min': min_depth,
                'max': max_depth
            }
    
    # Save updated transforms.json with depth information
    # Only save if we generated the transforms (not when we read from source)
    if args.save_depth and not (args.shading_mode == 'normal' and 'renders3-normal' in args.output_root):
        transforms_output_path = os.path.join(output_dir, 'transforms.json')
        with open(transforms_output_path, 'w') as f:
            json.dump(transforms_data, f, indent=4)
        print(f"Updated camera transforms with depth info to {transforms_output_path}")
    
    print(f"  Completed rendering {len(transforms_data['frames'])} views to {output_dir}")

def main():
    parser = argparse.ArgumentParser(description='Render 3D meshes using nvdiffrast with camera poses from transforms.json files')
    parser.add_argument('--mesh_root', type=str, default="/ibex/tmp/TRELLIS-500K/megapose_data/shapenetcorev2/models_orig/", help='Root directory containing subfolders with GLB mesh files')
    parser.add_argument('--output_root', type=str, default="/ibex/tmp/TRELLIS-500K/megapose_data/shapenetcorev2/renders3-color/", help='Root output directory for rendered images')
    parser.add_argument('--resolution', type=int, default=512, help='Render resolution (default: 512)')
    parser.add_argument('--device', type=str, default='cuda', help='Device to run on (default: cuda)')
    parser.add_argument('--save_depth', action='store_true', help='Save depth maps')
    parser.add_argument('--shading_mode', type=str, default='texture', choices=['texture', 'vertex_color', 'normal', 'random'], 
                       help='Shading mode: texture (use UV+texture, preferred), vertex_color (vertex colors), normal (normal-based), or random (random colors per face)')
    parser.add_argument('--near', type=float, default=0.1, help='Near clipping plane (default: 0.1)')
    parser.add_argument('--far', type=float, default=100.0, help='Far clipping plane (default: 100.0)')
    parser.add_argument('--skip_normalization', action='store_false', help='Skip mesh normalization (use when meshes are already normalized)')
    parser.add_argument('--ssaa_factor', type=int, default=1, help='SSAA (Super Sampling Anti-Aliasing) factor - render at higher resolution and downsample (default: 4, set to 1 to disable)')
    parser.add_argument('--ssaa_filter', type=str, default='lanczos', choices=['bilinear', 'area', 'lanczos'], 
                       help='SSAA downsampling filter (default: lanczos)')
    parser.add_argument('--flip_uv_v', action='store_false', help='Flip V coordinate of UV mapping (try this if texture appears upside down)')
    parser.add_argument('--flip_uv_u', action='store_true', help='Flip U coordinate of UV mapping (try this if texture appears mirrored horizontally)')
    parser.add_argument('--debug_single', type=str, help='Debug single subfolder by name (render only this subfolder)')
    parser.add_argument("--rank_size", type=int, default=1, help="Number of processes to run in parallel. Default is 1, which means no parallel processing.")
    parser.add_argument("--rank_id", type=int, default=0, help="Rank ID for parallel processing. Default is 0, which means no parallel processing.")
    parser.add_argument('--n_views', type=int, default=50, help='Number of camera views to generate (default: 50)')
    parser.add_argument('--camera_radius', type=float, default=0.4, help='Distance from origin to camera (default: 0.4)')
    parser.add_argument('--camera_angle_x', type=float, default=0.6981317007977318, help='Horizontal field of view in radians (default: 0.6981317007977318)')
    parser.add_argument('--seed', type=int, default=42, help='Random seed for reproducibility (default: 42)')

    args = parser.parse_args()
    
    # Set random seeds for reproducibility
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(args.seed)
        torch.cuda.manual_seed_all(args.seed)
    print(f"Random seed set to: {args.seed}")
    
    # Create output root directory
    os.makedirs(args.output_root, exist_ok=True)
    
    # Check if CUDA is available
    if args.device == 'cuda' and not torch.cuda.is_available():
        print("CUDA not available, falling back to CPU")
        args.device = 'cpu'
    
    print(f"Using device: {args.device}")
    print(f"SSAA settings: {args.ssaa_factor}x factor with {args.ssaa_filter} filtering" + 
          (" (disabled)" if args.ssaa_factor == 1 else ""))
    
    # Find matching subfolder pairs
    print(f"Searching for subfolder pairs in:")
    print(f"  Mesh root: {args.mesh_root}")
    
    if 'shapenetcorev2' not in args.mesh_root.lower():
        subfolder_pairs = find_subfolder_pairs(args.output_root, args.mesh_root)
    else:
        subfolder_pairs = find_subfolder_pairs_shapenet(args.output_root, args.mesh_root)
    
    # Filter for debug_single if specified
    if args.debug_single:
        subfolder_pairs = [(name, trans, mesh) for name, trans, mesh in subfolder_pairs if name == args.debug_single]
        if not subfolder_pairs:
            print(f"Debug subfolder '{args.debug_single}' not found!")
            return
        print(f"Debug mode: processing only subfolder '{args.debug_single}'")
    
    if not subfolder_pairs:
        print("No matching subfolder pairs found!")
        return
    
    print(f"Found {len(subfolder_pairs)} subfolder pairs to process")
    
    # Filter subfolder pairs based on rank size and ID for parallel processing
    if args.rank_size > 1:
        # Split work among ranks
        subfolder_pairs = [pair for i, pair in enumerate(subfolder_pairs) if i % args.rank_size == args.rank_id]
        print(f"Rank {args.rank_id} processing {len(subfolder_pairs)} subfolder pairs out of total")
    else:
        print(f"Single process mode: processing all {len(subfolder_pairs)} subfolder pairs")
    
    if not subfolder_pairs:
        print(f"No subfolder pairs assigned to rank {args.rank_id}")
        return
    
    # Add UV flipping info to output
    uv_flip_info = ""
    if args.flip_uv_u or args.flip_uv_v:
        flips = []
        if args.flip_uv_u:
            flips.append("U")
        if args.flip_uv_v:
            flips.append("V")
        uv_flip_info = f" (UV flipping: {', '.join(flips)})"
    print(f"UV coordinate settings{uv_flip_info}")
    
    # Process each subfolder pair
    for subfolder_name, transforms_path, mesh_path in tqdm(subfolder_pairs, desc=f"Processing subfolders (rank {args.rank_id})"):
        try:
            process_subfolder_pair(subfolder_name, transforms_path, mesh_path, args)
        except Exception as e:
            print(f"Error processing subfolder {subfolder_name}: {str(e)}")
            print(f"Skipping subfolder {subfolder_name} and continuing...")
            # rm -rf output dir to avoid partial results
            output_dir = os.path.join(args.output_root, subfolder_name)
            if os.path.exists(output_dir):
                shutil.rmtree(output_dir)
            continue
            
    
    print(f"\n{'='*60}")
    print(f"All rendering complete! Results saved to {args.output_root}")
    print(f"Rank {args.rank_id} processed {len(subfolder_pairs)} subfolders successfully")

if __name__ == '__main__':
    main()
